#!/bin/bash

T=$(mktemp -d)
trap "rm -rf $T" EXIT

cat >$T/debian_packages <<...
curl
fzf
git
git-lfs
jp2a
locales
python3-pip
ripgrep
silversearcher-ag
sudo
tmux
vim
xz-utils
...

cat >$T/python_packages <<...
black
isort
python-language-server
...

cat >$T/locale.gen <<...
en_US.UTF-8 UTF-8
en_GB.UTF-8 UTF-8
...

cat >$T/init <<'...'
adduser \
  --gecos '' \
  --disabled-password \
  --uid $TARGET_UID \
  --home $TARGET_HOME \
  --no-create-home \
  $TARGET_USER

echo "$TARGET_USER ALL=(ALL:ALL) NOPASSWD:ALL" >/etc/sudoers.d/$TARGET_USER

export TERM=$TARGET_TERM

base64 -d <hi | zcat | jp2a --colors --color-depth=24 -

cd "$TARGET_DIR"
sudo \
  --preserve-env \
  --set-home \
  --user $TARGET_USER \
  -- \
  $TARGET_SHELL -i
...

cat >$T/hi <<'...'
H4sICApjG2IAA3kuanBnAPt/4/8DBgEvN083BkZGBgZGIGT4f5vBmeE/pQBoCCPFhhxgEORgqGC4
xswoyMAkyMgsyPj/CIM40KkgxyIBRiZmoIS8AEickYUZIckoqGjoGFjIJJQ4EahADEMjUCdIXBBT
XPD/LQYeoElMgsyCDPYMZ9xWe51AVTKDjbGhgYuha2PQigawAPvxtWwHgDQzwwk2h+S9DAwODCxu
DWu1FcCy3OpRXFxgFrPsCyCpoGTCDDWSOUAEYqTE5zdAUkBQijFpaSBYhG2BBkTK8PkNEHXKhOmo
1yKwCG8D5+T7G4yYGjgn8DQsYAYbpHGBwWRNA1Q2j5HRgWUPo+UfVgaJBVBZnZBVQOc0ZKh94lvA
AHUNyM1sgksZGEJTGIQdLRfs4OJrgMpNffRCZxfQ1cwclw7oMPCGrDzRPYWHlUFEGug5388a8vn1
ByLrDUQYGLtPGFosALqQZ7G3gvCB1hlSZ0JyREUcDUtcnY/vABsHxBoGPDfviDE1MBj1mnUcfbWq
9JXigktcGhxMiyq+i8pCrHQISGBIK3RcwMAyZ2nYhHRRE16FVV2MqzoXMJ27dxVoLQMLKzB2GtLu
M2wKCDA0iTHxbFrFs0pBY8GCDq2OhjtzRUVEBMARaHdBYrvjSgMpFgdXUzfGEgYf1gcgCVlRhgCQ
PAtb3QbOjwcygEz5/zcBGJnaWggDAAA=
...

cat >$T/Dockerfile <<...
FROM ubuntu:jammy

COPY debian_packages .
RUN apt update
RUN env DEBIAN_FRONTEND=noninteractive xargs apt install --yes <debian_packages

COPY python_packages .
RUN pip3 install -r python_packages

COPY locale.gen /etc/locale.gen
RUN locale-gen

COPY hi .

COPY init .
CMD bash -i
...

docker build --tag lets-get-creative $T

docker run \
  --tty \
  --interactive \
  --mount "type=bind,source=$HOME,target=$HOME" \
  --mount "type=bind,source=$SSH_AUTH_SOCK,target=$SSH_AUTH_SOCK" \
  --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
  --env TARGET_USER=$USER \
  --env TARGET_UID=$UID \
  --env TARGET_HOME=$HOME \
  --env TARGET_DIR=$PWD \
  --env TARGET_SHELL=$SHELL \
  --env TARGET_TERM=$TERM \
  lets-get-creative bash init
